-- ================================================================
-- CLOSING EMAS AREA MEDAN 1 - SUPABASE / POSTGRESQL
-- Jalankan seluruh file ini di Supabase Dashboard -> SQL Editor.
-- Aman untuk instalasi baru. Jangan simpan service_role key di frontend.
-- ================================================================

create extension if not exists citext with schema extensions;
create extension if not exists pgcrypto with schema extensions;

-- -----------------------------
-- TABEL PROFIL & AKSES
-- -----------------------------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  role text not null check (role in ('Admin','Umum','Disabled')),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name extensions.citext not null unique,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  branch extensions.citext not null,
  outlet extensions.citext not null,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  constraint locations_branch_outlet_key unique(branch,outlet)
);

create table if not exists public.realizations (
  id text primary key,
  date date not null,
  branch text not null,
  outlet text not null,
  customer text not null,
  contract extensions.citext not null unique,
  product text not null,
  tenor integer not null check (tenor > 0),
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict
);
create index if not exists idx_realizations_date on public.realizations(date);
create index if not exists idx_realizations_branch_outlet on public.realizations(branch,outlet);

create table if not exists public.mulia_records (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  signature text not null unique,
  created_at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict
);

create table if not exists public.risk_records (
  id bigint generated by default as identity primary key,
  risk_type text not null check (risk_type in ('kol1','lar','npl')),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_risk_type on public.risk_records(risk_type);

create table if not exists public.risk_meta (
  id integer primary key check (id = 1),
  file_name text not null default '',
  last_import text not null default '',
  sheet_name text not null default '',
  source_rows integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.settings(key,value) values
  ('monthly_target','8000000000'),
  ('mulia_last_import','')
on conflict (key) do nothing;

insert into public.risk_meta(id) values(1) on conflict(id) do nothing;

insert into public.products(name) values
  ('KCA Emas'),('Gadai Emas'),('Arrum Emas'),('Emas Angsuran'),('Mulia'),('Produk Emas Lainnya')
on conflict(name) do nothing;

insert into public.locations(branch,outlet) values
  ('10001:CP MEDAN UTAMA', '10001:CP MEDAN UTAMA'),
  ('10001:CP MEDAN UTAMA', '10002:UPC TITI KUNING'),
  ('10001:CP MEDAN UTAMA', '10003:UPC KATAMSO'),
  ('10001:CP MEDAN UTAMA', '10004:UPC MEDAN PLASA'),
  ('10001:CP MEDAN UTAMA', '10005:UPC PUSAT PASAR'),
  ('10001:CP MEDAN UTAMA', '10006:UPC GAJAHMADA'),
  ('10001:CP MEDAN UTAMA', '10007:UPC SIMPANG UISU'),
  ('10001:CP MEDAN UTAMA', '10008:UPC MULTATULI'),
  ('10001:CP MEDAN UTAMA', '10200:UPC MEDAN THAMRIN'),
  ('10009:CP LABUHAN DELI', '10009:CP LABUHAN DELI'),
  ('10009:CP LABUHAN DELI', '10010:UPC MARELAN'),
  ('10009:CP LABUHAN DELI', '10011:UPC BELAWAN'),
  ('10009:CP LABUHAN DELI', '10012:UPC HAMPARAN PERAK'),
  ('10009:CP LABUHAN DELI', '10013:UPC MARTUBUNG'),
  ('10009:CP LABUHAN DELI', '10014:UPC MARELAN 2'),
  ('10016:CP PANCUR BATU', '10016:CP PANCUR BATU'),
  ('10016:CP PANCUR BATU', '10017:UPC TANJUNG ANOM'),
  ('10016:CP PANCUR BATU', '10018:UPC SELAYANG'),
  ('10016:CP PANCUR BATU', '10019:UPC KARYA KASIH'),
  ('10025:CP TANJUNG PURA', '10025:CP TANJUNG PURA'),
  ('10025:CP TANJUNG PURA', '10026:UPC STABAT'),
  ('10025:CP TANJUNG PURA', '10027:UPC KUALA BEGUMIT'),
  ('10025:CP TANJUNG PURA', '10028:UPC PERDAMAIAN STABAT'),
  ('10025:CP TANJUNG PURA', '17001:UPC BRI UNIT BATANG SERANGAN'),
  ('10029:CP PKL BRANDAN', '10029:CP PKL BRANDAN'),
  ('10029:CP PKL BRANDAN', '10030:UPC PANGKALAN SUSU'),
  ('10029:CP PKL BRANDAN', '10031:UPC PELAWI'),
  ('10029:CP PKL BRANDAN', '10032:UPC SEI LAPAN'),
  ('10029:CP PKL BRANDAN', '10033:UPC BESITANG'),
  ('10034:CP BINJAI', '10034:CP BINJAI'),
  ('10034:CP BINJAI', '10035:UPC BINJAI UTARA'),
  ('10034:CP BINJAI', '10036:UPC PASAR TAVIP'),
  ('10034:CP BINJAI', '10037:UPC MERDEKA'),
  ('10034:CP BINJAI', '10038:UPC SOEKARNO HATTA'),
  ('10034:CP BINJAI', '10039:UPC BANGKATAN'),
  ('10034:CP BINJAI', '14375:UPC KUALA'),
  ('10034:CP BINJAI', '14428:UPC TANAH SERIBU'),
  ('10124:CP MEDAN SUNGGAL', '10124:CP MEDAN SUNGGAL'),
  ('10124:CP MEDAN SUNGGAL', '10125:UPC PASAR SUNGGAL'),
  ('10124:CP MEDAN SUNGGAL', '10126:UPC CINTA DAMAI'),
  ('10124:CP MEDAN SUNGGAL', '10127:UPC AMAL'),
  ('10124:CP MEDAN SUNGGAL', '10128:UPC ASOKA'),
  ('10124:CP MEDAN SUNGGAL', '10129:UPC BATANG HARI'),
  ('10130:CP KRAKATAU', '10130:CP KRAKATAU'),
  ('10130:CP KRAKATAU', '10131:UPC PERJUANGAN'),
  ('10130:CP KRAKATAU', '10132:UPC PANCING'),
  ('10130:CP KRAKATAU', '10133:UPC SIDORUKUN'),
  ('10130:CP KRAKATAU', '10134:UPC MAHAMERU'),
  ('10130:CP KRAKATAU', '10135:UPC BAYANGKARA'),
  ('10130:CP KRAKATAU', '14393:UPC LODENDANG'),
  ('10136:CP KABANJAHE', '10136:CP KABANJAHE'),
  ('10136:CP KABANJAHE', '10137:UPC BRASTAGI'),
  ('10136:CP KABANJAHE', '10138:UPC TIGA PANAH'),
  ('10136:CP KABANJAHE', '14373:UPC TIGA BINANGA'),
  ('10136:CP KABANJAHE', '14427:UPC LAU CIMBA'),
  ('10136:CP KABANJAHE', '17004:UPC BRI UNIT SARIBU DOLOK'),
  ('10136:CP KABANJAHE', '17104:UPC BRI UNIT TIGANDERKET'),
  ('10136:CP KABANJAHE', '17105:UPC BRI UNIT LAUBALENG'),
  ('10139:CP MEDAN KARYA', '10139:CP MEDAN KARYA'),
  ('10139:CP MEDAN KARYA', '10141:UPC PASAR IV'),
  ('10139:CP MEDAN KARYA', '10142:UPC ADAM MALIK'),
  ('10154:CP SIDIKALANG', '10154:CP SIDIKALANG'),
  ('10154:CP SIDIKALANG', '10155:UPC SUMBUL'),
  ('10154:CP SIDIKALANG', '14372:UPC TIGA LINGGA'),
  ('10154:CP SIDIKALANG', '17041:UPC BRI UNIT SALAK SIDIKALANG'),
  ('10154:CP SIDIKALANG', '17230:UPC BRI UNIT PARONGIL'),
  ('10165:CP GAHARU', '10165:CP GAHARU'),
  ('10165:CP GAHARU', '10166:UPC SERDANG'),
  ('10165:CP GAHARU', '10167:UPC KAMPUNG DURIAN'),
  ('10165:CP GAHARU', '10168:UPC PRINTIS'),
  ('10165:CP GAHARU', '10169:UPC GLUGUR'),
  ('10176:CP KP LALANG', '10176:CP KP LALANG'),
  ('10176:CP KP LALANG', '10177:UPC DISKI'),
  ('10176:CP KP LALANG', '10178:UPC PONDOK KELAPA'),
  ('10176:CP KP LALANG', '10179:UPC KLAMBIR LIMA'),
  ('10176:CP KP LALANG', '10180:UPC RING ROAD'),
  ('10176:CP KP LALANG', '10181:UPC SEMAYANG'),
  ('10176:CP KP LALANG', '10182:UPC MEDAN KRIYO'),
  ('10176:CP KP LALANG', '10183:UPC KLUMPANG'),
  ('10176:CP KP LALANG', '17032:UPC BRI UNIT KLUMPANG'),
  ('10185:CP PULO BRAYAN', '10185:CP PULO BRAYAN'),
  ('10185:CP PULO BRAYAN', '10186:UPC TITI PAPAN'),
  ('10185:CP PULO BRAYAN', '10187:UPC VETERAN'),
  ('10185:CP PULO BRAYAN', '10188:UPC MABAR'),
  ('10189:CP HELVETIA', '10189:CP HELVETIA'),
  ('10189:CP HELVETIA', '10190:UPC PASAR HELVETIA'),
  ('10189:CP HELVETIA', '10191:UPC SEI SIKAMBING'),
  ('10189:CP HELVETIA', '10192:UPC PLASA MILENIUM'),
  ('10204:CP MEDAN PETISAH', '10204:CP MEDAN PETISAH'),
  ('10204:CP MEDAN PETISAH', '10205:UPC GATOT SUBROTO'),
  ('10204:CP MEDAN PETISAH', '10207:UPC SEKIP'),
  ('10204:CP MEDAN PETISAH', '10208:UPC MEDAN FAIR'),
  ('60075:CPS AR.HAKIM', '60075:CPS AR.HAKIM'),
  ('60075:CPS AR.HAKIM', '60078:UPS AHMAD YANI SIANTAR'),
  ('60075:CPS AR.HAKIM', '60079:UPS WAHIDIN SIANTAR'),
  ('60075:CPS AR.HAKIM', '60919:UPS AYAHANDA')
on conflict(branch,outlet) do nothing;

-- -----------------------------
-- PROFIL OTOMATIS DARI SUPABASE AUTH
-- Email internal hanya dipakai untuk login username Area / Outlet.
-- -----------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
  v_role text;
begin
  if lower(coalesce(new.email,'')) = 'area@closingemas.app' then
    v_username := 'Area';
    v_role := 'Admin';
  elsif lower(coalesce(new.email,'')) = 'outlet@closingemas.app' then
    v_username := 'Outlet';
    v_role := 'Umum';
  else
    v_username := coalesce(nullif(new.raw_user_meta_data->>'username',''), split_part(coalesce(new.email,'user'),'@',1) || '_' || left(new.id::text,8));
    v_role := 'Disabled';
  end if;

  insert into public.profiles(user_id,username,role)
  values(new.id,v_username,v_role)
  on conflict(user_id) do update set username=excluded.username, role=excluded.role;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_closing_emas on auth.users;
create trigger on_auth_user_created_closing_emas
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Backfill jika user Area / Outlet sudah dibuat sebelum SQL ini dijalankan.
insert into public.profiles(user_id,username,role)
select id,'Area','Admin' from auth.users where lower(email)='area@closingemas.app'
on conflict(user_id) do update set username='Area',role='Admin';

insert into public.profiles(user_id,username,role)
select id,'Outlet','Umum' from auth.users where lower(email)='outlet@closingemas.app'
on conflict(user_id) do update set username='Outlet',role='Umum';

-- -----------------------------
-- HELPER KEAMANAN RLS
-- -----------------------------
create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role in ('Admin','Umum')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = 'Admin'
  );
$$;

-- -----------------------------
-- RPC BULK / SNAPSHOT
-- -----------------------------
create or replace function public.bulk_insert_products(p_names text[])
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  raw_name text;
  clean_name text;
  affected integer;
  added integer := 0;
  skipped integer := 0;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  foreach raw_name in array coalesce(p_names,array[]::text[]) loop
    clean_name := btrim(regexp_replace(coalesce(raw_name,''), '\s+', ' ', 'g'));
    if clean_name = '' then continue; end if;
    insert into public.products(name,created_by) values(clean_name,auth.uid()) on conflict(name) do nothing;
    get diagnostics affected = row_count;
    if affected=1 then added:=added+1; else skipped:=skipped+1; end if;
  end loop;
  return jsonb_build_object('added',added,'skipped',skipped);
end;
$$;

create or replace function public.bulk_insert_locations(p_locations jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  item jsonb;
  b text;
  o text;
  affected integer;
  added integer := 0;
  skipped integer := 0;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  for item in select value from jsonb_array_elements(coalesce(p_locations,'[]'::jsonb)) loop
    b := btrim(regexp_replace(coalesce(item->>'branch',''), '\s+', ' ', 'g'));
    o := btrim(regexp_replace(coalesce(item->>'outlet',''), '\s+', ' ', 'g'));
    if b='' or o='' then continue; end if;
    insert into public.locations(branch,outlet,created_by) values(b,o,auth.uid()) on conflict(branch,outlet) do nothing;
    get diagnostics affected = row_count;
    if affected=1 then added:=added+1; else skipped:=skipped+1; end if;
  end loop;
  return jsonb_build_object('added',added,'skipped',skipped);
end;
$$;

create or replace function public.bulk_insert_mulia(p_records jsonb, p_last_import text default '')
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  item jsonb;
  row_data jsonb;
  rec_id text;
  sig text;
  affected integer;
  added integer := 0;
  skipped integer := 0;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  for item in select value from jsonb_array_elements(coalesce(p_records,'[]'::jsonb)) loop
    row_data := coalesce(item->'data','{}'::jsonb);
    if jsonb_typeof(row_data) <> 'object' or row_data='{}'::jsonb then continue; end if;
    rec_id := coalesce(nullif(item->>'id',''),'m' || replace(gen_random_uuid()::text,'-',''));
    sig := md5(row_data::text);
    insert into public.mulia_records(id,data,signature,created_by)
    values(rec_id,row_data,sig,auth.uid())
    on conflict do nothing;
    get diagnostics affected = row_count;
    if affected=1 then added:=added+1; else skipped:=skipped+1; end if;
  end loop;
  if btrim(coalesce(p_last_import,'')) <> '' then
    insert into public.settings(key,value) values('mulia_last_import',p_last_import)
    on conflict(key) do update set value=excluded.value;
  end if;
  return jsonb_build_object('added',added,'skipped',skipped);
end;
$$;

create or replace function public.delete_all_mulia()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted integer;
begin
  if not public.is_active_user() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  delete from public.mulia_records;
  get diagnostics deleted = row_count;
  insert into public.settings(key,value) values('mulia_last_import','')
  on conflict(key) do update set value='';
  return jsonb_build_object('deleted',deleted);
end;
$$;

create or replace function public.replace_risk_snapshot(p_records jsonb, p_meta jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  k text;
  c_kol1 integer := 0;
  c_lar integer := 0;
  c_npl integer := 0;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  delete from public.risk_records;
  foreach k in array array['kol1','lar','npl'] loop
    for item in select value from jsonb_array_elements(coalesce(p_records->k,'[]'::jsonb)) loop
      if jsonb_typeof(item)='object' then
        insert into public.risk_records(risk_type,data) values(k,item);
        if k='kol1' then c_kol1:=c_kol1+1;
        elsif k='lar' then c_lar:=c_lar+1;
        else c_npl:=c_npl+1;
        end if;
      end if;
    end loop;
  end loop;
  insert into public.risk_meta(id,file_name,last_import,sheet_name,source_rows,updated_by,updated_at)
  values(1,coalesce(p_meta->>'fileName',''),coalesce(p_meta->>'lastImport',''),coalesce(p_meta->>'sheetName',''),coalesce(nullif(p_meta->>'sourceRows','')::integer,0),auth.uid(),now())
  on conflict(id) do update set
    file_name=excluded.file_name,last_import=excluded.last_import,sheet_name=excluded.sheet_name,
    source_rows=excluded.source_rows,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
  return jsonb_build_object('counts',jsonb_build_object('kol1',c_kol1,'lar',c_lar,'npl',c_npl));
end;
$$;

create or replace function public.clear_risk_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted integer;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN' using errcode='42501'; end if;
  delete from public.risk_records;
  get diagnostics deleted = row_count;
  insert into public.risk_meta(id,file_name,last_import,sheet_name,source_rows,updated_by,updated_at)
  values(1,'','','',0,auth.uid(),now())
  on conflict(id) do update set file_name='',last_import='',sheet_name='',source_rows=0,updated_by=auth.uid(),updated_at=now();
  return jsonb_build_object('deleted',deleted);
end;
$$;

-- -----------------------------
-- ROW LEVEL SECURITY
-- -----------------------------
alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.products enable row level security;
alter table public.locations enable row level security;
alter table public.realizations enable row level security;
alter table public.mulia_records enable row level security;
alter table public.risk_records enable row level security;
alter table public.risk_meta enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated using (user_id=auth.uid());

drop policy if exists settings_read_active on public.settings;
create policy settings_read_active on public.settings for select to authenticated using (public.is_active_user());
drop policy if exists settings_admin_insert on public.settings;
create policy settings_admin_insert on public.settings for insert to authenticated with check (public.is_admin());
drop policy if exists settings_admin_update on public.settings;
create policy settings_admin_update on public.settings for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists products_read_active on public.products;
create policy products_read_active on public.products for select to authenticated using (public.is_active_user());
drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products for insert to authenticated with check (public.is_admin());
drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products for delete to authenticated using (public.is_admin());

drop policy if exists locations_read_active on public.locations;
create policy locations_read_active on public.locations for select to authenticated using (public.is_active_user());
drop policy if exists locations_admin_insert on public.locations;
create policy locations_admin_insert on public.locations for insert to authenticated with check (public.is_admin());
drop policy if exists locations_admin_delete on public.locations;
create policy locations_admin_delete on public.locations for delete to authenticated using (public.is_admin());

drop policy if exists realizations_read_active on public.realizations;
create policy realizations_read_active on public.realizations for select to authenticated using (public.is_active_user());
drop policy if exists realizations_insert_active on public.realizations;
create policy realizations_insert_active on public.realizations for insert to authenticated with check (public.is_active_user() and created_by=auth.uid());
drop policy if exists realizations_admin_delete on public.realizations;
create policy realizations_admin_delete on public.realizations for delete to authenticated using (public.is_admin());

drop policy if exists mulia_read_active on public.mulia_records;
create policy mulia_read_active on public.mulia_records for select to authenticated using (public.is_active_user());
drop policy if exists mulia_admin_insert on public.mulia_records;
create policy mulia_admin_insert on public.mulia_records for insert to authenticated with check (public.is_admin());
drop policy if exists mulia_delete_active on public.mulia_records;
create policy mulia_delete_active on public.mulia_records for delete to authenticated using (public.is_active_user());

drop policy if exists risk_read_active on public.risk_records;
create policy risk_read_active on public.risk_records for select to authenticated using (public.is_active_user());
drop policy if exists risk_admin_insert on public.risk_records;
create policy risk_admin_insert on public.risk_records for insert to authenticated with check (public.is_admin());
drop policy if exists risk_admin_delete on public.risk_records;
create policy risk_admin_delete on public.risk_records for delete to authenticated using (public.is_admin());

drop policy if exists risk_meta_read_active on public.risk_meta;
create policy risk_meta_read_active on public.risk_meta for select to authenticated using (public.is_active_user());
drop policy if exists risk_meta_admin_insert on public.risk_meta;
create policy risk_meta_admin_insert on public.risk_meta for insert to authenticated with check (public.is_admin());
drop policy if exists risk_meta_admin_update on public.risk_meta;
create policy risk_meta_admin_update on public.risk_meta for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- -----------------------------
-- GRANT DATA API (RLS TETAP MEMBATASI AKSES)
-- -----------------------------
revoke all on public.profiles,public.settings,public.products,public.locations,public.realizations,public.mulia_records,public.risk_records,public.risk_meta from anon;
grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select,insert,update on public.settings to authenticated;
grant select,insert,delete on public.products to authenticated;
grant select,insert,delete on public.locations to authenticated;
grant select,insert,delete on public.realizations to authenticated;
grant select,insert,delete on public.mulia_records to authenticated;
grant select,insert,delete on public.risk_records to authenticated;
grant select,insert,update,delete on public.risk_meta to authenticated;
grant usage,select on all sequences in schema public to authenticated;

revoke execute on function public.bulk_insert_products(text[]) from public, anon;
revoke execute on function public.bulk_insert_locations(jsonb) from public, anon;
revoke execute on function public.bulk_insert_mulia(jsonb,text) from public, anon;
revoke execute on function public.delete_all_mulia() from public, anon;
revoke execute on function public.replace_risk_snapshot(jsonb,jsonb) from public, anon;
revoke execute on function public.clear_risk_snapshot() from public, anon;
grant execute on function public.bulk_insert_products(text[]) to authenticated;
grant execute on function public.bulk_insert_locations(jsonb) to authenticated;
grant execute on function public.bulk_insert_mulia(jsonb,text) to authenticated;
grant execute on function public.delete_all_mulia() to authenticated;
grant execute on function public.replace_risk_snapshot(jsonb,jsonb) to authenticated;
grant execute on function public.clear_risk_snapshot() to authenticated;

-- SELESAI.
-- Setelah SQL ini dijalankan, buat dua user di Authentication -> Users:
--   area@closingemas.app   password: Area@123!
--   outlet@closingemas.app password: Outlet@123!
-- Trigger di atas otomatis memberi role Admin / Umum.
